defaults: &defaults
  adapter: mysql
  username: root
  password: oogabooga
  host: 127.0.0.1

development:
  <<: *defaults
  database: shaker_dev

test:
  <<: *defaults
  database: shaker_test

production:
  <<: *defaults
  database: shaker_dev
